-- XXX: impatient.nvim will only be required until https://github.com/neovim/neovim/pull/15436 is merged
if not pcall(require, "impatient") then
  print "failed to load impatient.nvim"
end

require "user.options"
require "user.keybindings"
require "user.plugins"
require "user.colorscheme"
require "user.icons"
require "user.notify"
require "user.autopairs"
require "user.cmp"
require "user.comment"
require "user.lsp"
require "user.telescope"
require "user.telescope-file-browser"
require "user.treesitter"
require "user.gitsigns"
require "user.nvim-tree"
require "user.bufferline"
require "user.lualine"
require "user.toggleterm"
require "user.project"
require "user.blankline"
require "user.alpha"
require "user.whichkey"
require "user.autocommands"
require "user.colorizer"
require "user.quickscope"
require "user.neoscroll"
require "user.todo-comments"
require "user.bookmark"
require "user.ts-context"
require "user.symbol-outline"
require "user.git-blame"
require "user.gitlinker"
require "user.renamer"
require "user.spectre"
require "user.sniprun"
require "user.zen-mode"
require "user.twilight"
require "user.functions"
require "user.registers"
require "user.copilot"
require "user.gps"
require "user.illuminate"
